#!/usr/bin/env python
import dscan, sys, os

prev_cwd = os.getcwd()

p = os.path.dirname(dscan.__file__)
sys.path.append(p)
os.chdir(p)

import droopescan
if os.getenv('DROOPESCAN_PROFILE'):
    import cProfile
    cProfile.run("droopescan.main(prev_cwd)", sort="cumtime")
else:
    droopescan.main(prev_cwd)
